# Spider.yaml
USER_AGENT: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36'
ROBOTSTXT_OBEY: True
COOKIES_ENABLED: False
AJAXCRAWL_ENABLED: True
LOG_ENABLED: False
DOWNLOAD_DELAY: 0
CONCURRENT_REQUESTS: 100
RETRY_ENABLED: True
DOWNLOAD_TIMEOUT: 15
REDIRECT_ENABLED: True
ITEM_PIPELINES: {
    'FAQ.scraper.pipelines.DropPipeline': 200,
#    'FAQ.scraper.pipelines.LocalWriterPipeline': 300
    'FAQ.scraper.pipelines.JsonWriterPipeline': 300

    }
spiders_limit: 50