# Spider.yaml
USER_AGENT: "Scrapy/VERSION (+https://scrapy.org)"
ROBOTSTXT_OBEY: True
COOKIES_ENABLED: True
LOG_ENABLED: False
DOWNLOAD_DELAY: 2
CONCURRENT_REQUESTS: 16
RETRY_ENABLED: True
DOWNLOAD_TIMEOUT: 15
REDIRECT_ENABLED: True
ITEM_PIPELINES: {
    'FAQ.scraper.pipelines.DropPipeline': 200,
#    'FAQ.scraper.pipelines.LocalWriterPipeline': 300
    'FAQ.scraper.pipelines.JsonWriterPipeline': 300

    }
spiders_limit: 50
